language: python

matrix:
  include:
    - os: linux
      dist: Focal
      python: 3.7

before_install: 
  - chmod +x ./.travis/travis_before_install.sh
  - ./.travis/travis_before_install.sh

install:
  - pip3 install Cython
  - pip3 install pandas 
  - pip3 install numpy
  - pip3 install statsmodels
  - pip3 install sphinx
  - pip3 install numba
  - pyhton3 setup.py install --user

script:
  - grafimo -h
  - pytest

