# Control file for continuous integration testing at http://travis-ci.org/

language: python
sudo: required
os: linux
dist: bionic
compiler: gcc

python: 
  - "3.7"
  
addons: 
  apt:
    update: true
    packages: 
      - bc 
      - rs 
      - jq
      - samtools
      - cmake
      - protobuf-compiler
      - libprotoc-dev
      - libprotobuf-dev
      - libjansson-dev
      - libbz2-dev
      - libncurses5-dev
      - automake
      - libtool
      - curl
      - unzip
      - redland-utils
      - librdf-dev
      - pkg-config
      - wget 
      - gtk-doc-tools
      - raptor2-utils
      - rasqal-utils
      - bison
      - flex
      - gawk
      - libgoogle-perftools-dev
      - liblz4-dev
      - liblzma-dev
      - libcairo2-dev
      - libpixman-1-dev
      - libffi-dev
      - doxygen

before_install: 
  - cd ..
  - chmod +x ./GRAFIMO/.travis/travis_before_install.sh
  - ./GRAFIMO/.travis/travis_before_install.sh
  - cd GRAFIMO

install:
  - pip3 install Cython
  - pip3 install setuptools
  - pip3 install wheel
  - pip3 install pandas 
  - pip3 install numpy
  - pip3 install statsmodels
  - pip3 install sphinx
  - pip3 install numba
  - installationpath=$PWD
  - echo $installationpath
  - python3 setup.py install
  - cd tests
  - installationpath=$PWD
  - echo $installationpath

script:
  - grafimo -h
  - pytest
